### ISSUE TITLE
Windows development challenges...

### ISSUE THREAD

**Issue by stela5** [dmnsgn/frontend-boilerplate#13]
Not sure how many of these are my fault/naivete, but I figured I'd list them here in case others ran into them:

---

**Windows path too long** issue:
https://github.com/nodejs/node/issues/1849
https://github.com/remy/nodemon/issues/559

Workaround (see https://github.com/nodejs/node/issues/1849#issuecomment-107353317 and https://github.com/remy/nodemon/issues/559#issuecomment-112095486):
1. Create a _C:\npm_ directory
2. Add _C:\npm_ to the PATH environment variable
3. `npm config set prefix=C:\npm`

---

**node_gyp Windows dependencies** issue:
https://github.com/nodejs/node-gyp/issues/629
https://github.com/nodejs/node-gyp
1. Install Python 2.x (https://www.python.org/downloads/) and add it to the PATH environment variable
2. Install Visual Studio Express 2013 for Windows Desktop (https://www.microsoft.com/en-gb/download/details.aspx?id=44914)
3. Uninstall all Microsoft Visual C++ 2010 Redistributable installs (http://stackoverflow.com/a/23032807)
4. Install Microsoft Windows SDK for Windows 7 and .NET Framework 4 (https://www.microsoft.com/en-us/download/details.aspx?id=8279)

---

**Gulp** install issue: https://stackoverflow.com/questions/24010598/node-js-cannot-find-module-readable-stream

For some reason `npm install -g gulp babel` didn't work so I did them separately:

```
npm install -g gulp
npm install -g babel
npm install -g stylus
```

---

**EPERM** error: http://blogs.msdn.com/b/matt-harrington/archive/2012/02/23/how-to-fix-node-js-npm-permission-problems.aspx

I had to run `npm cache clean`

---

Error: Cannot find module '**gulp-stylus**'

`npm install --save-dev gulp-stylus`

---

Failed to load external module **babel-core/register**: https://github.com/yeoman/generator-gulp-webapp/issues/356#issuecomment-119576066

`npm install --save-dev babel-core`

---

...and after all that: success!

```
git clone --depth 1 https://github.com/dmnsgn/gulp-frontend-boilerplate.git && cd gulp-frontend-boilerplate && rd /s /q .git
npm run init
npm install
gulp
```

**Comment by stela5** [comment]
...oh, and one more:

```
npm cache clean && npm install -g napa
```

**Comment by stela5** [comment]
P.S. It appears `gulp` only works if run in a cmd prompt with *Administrator privileges*

**Comment by dmnsgn** [comment]
Thanks for all these tips on using it on Windows! Very helpful. I will see if I can fix some issues.
