### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)

### ISSUE THREAD

**Issue by dmnsgn** [dmnsgn/frontend-boilerplate#17]
`SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)`

**Solution:**
Change the order of transforms, moving `babelify` in the first position of the transform array in the `package.json`:
```json
  "browserify": {
    "transform": [
      "babelify",
      "aliasify",
      "brfs"
    ]
  },
```

**Comment by kirylpl** [comment]
@dmnsgn Thank you.

**Comment by kirylpl** [comment]
devDependencies needs `"babelify": "^8.x.x"` also as well.
