### ISSUE TITLE
Meta info for 'twitter:site' and 'twitter:creator' does not gets populated

### ISSUE THREAD

**Issue by 92arpitgoyal** [dmnsgn/frontend-boilerplate#23]
Hi, thanks for this great boilerplate, it is working great for me, using it for [my own portfolio](https://github.com/92arpitgoyal/92arpitgoyal.github.io)

As per src/templates/_meta.ejs file `twitter:site` and `twitter:creator` info should be populated by data.handle which looks wrong as per config/plugins/html.js but it should be `data.twitter.handle`.
I have sent a PR to fix the same. Please look into same.

**Comment by dmnsgn** [comment]
Good catch, I missed that in my latest refactor. Thanks for the PR.

**Comment by 92arpitgoyal** [comment]
@dmnsgn I can also send PR for adding 'keywords', 'author' meta info from package file.
